service: instagram

provider:
  name: aws
  runtime: nodejs10.x
  profile: my-personal

functions:
  upload-photo:
    handler: app.handler
    events:
      - http:
          method: get
          path: upload-photo
          cors:
            origins:
              - '*'
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin